version: '3'
services:
  web:
    build: .
    networks:
      - overlay
    ports:
     - "8080:8080"
  mongo:
    image: "mongo"
    networks:
       - overlay
    volumes:
       - mongodbdata:/data/db
    ports:
     - "27017:27017"

volumes:
  mongodbdata:

networks:
  overlay:
